# Generated by Django 4.2 on 2023-04-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('raca', models.CharField(default='', max_length=50)),
                ('classe', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField(default='', max_length=300)),
                ('tags', models.ManyToManyField(to='main_site.tag')),
            ],
        ),
    ]
