# Generated by Django 4.2 on 2023-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_personagemoriginalmodel_delete_personagemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagemoriginalmodel',
            name='tipo_personagem',
            field=models.CharField(choices=[('Original', 'Original'), ('Recreation', 'Recreation')], default='Original'),
        ),
    ]
