# Generated by Django 4.2 on 2023-04-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_personagemoriginalmodel_tipo_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagemoriginalmodel',
            name='backstory',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personagemoriginalmodel',
            name='descricao',
            field=models.TextField(default='', max_length=250),
        ),
    ]
